### ISSUE TITLE
Blog posts for 2022 don't show up on the main page

### ISSUE THREAD

**Issue by Ananya-Joshi** [cmu-csd-phd/csd-blog#5]
I've created a new folder for 2022 in the website/content and copied over the index template, but I'm unable to see my blog post on the main page, but I can access my blog via tags. 

On the [Zola theme](https://github.com/getzola/even), it says: 
"It also requires to put the posts in the root of the content folder"

Let me know what I should do to fix this. 

<img width="1111" alt="Screen Shot 2022-01-06 at 7 07 57 PM" src="https://user-images.githubusercontent.com/11541884/148470006-cd3552b7-b421-4543-bbac-a05f75fc382b.png">
<img width="987" alt="Screen Shot 2022-01-06 at 7 07 49 PM" src="https://user-images.githubusercontent.com/11541884/148470008-e54a1ffd-e91d-4792-a608-4c2642eb61c2.png">

**Comment by jaybosamiya** [comment]
Have you followed the instructions from the README? (https://github.com/cmu-csd-phd/csd-blog/blob/main/README.md?plain=1#L22-L24)
> If the folder for the current year does not exist, make a new folder, copying `_index.md` from the previous year into the directory first. 

If that `_index.md` is not copied over, then it will not show up on the main page.

**Comment by Ananya-Joshi** [comment]
I copied over the _index.md from 2021 to 2022 so that there are two files in the 2022 folder, the _index.md and my blog post, and I haven't been able to get my blog post to show up on the Home page.

**Comment by jaybosamiya** [comment]
Placing the `_index.md` file into the right directory immediately fixes the issue on my end, so yes, please do send over of your repository and I can take a look.

**Comment by jaybosamiya** [comment]
Also, fwiw, just to prevent accidentally forgetting the inclusion of `_index.md` in future years, I've now pushed some code to make it automatic going forward (https://github.com/cmu-csd-phd/csd-blog/commit/d7d1ce42886ed779396aa52694d333733e15f448)

**Comment by Ananya-Joshi** [comment]
Here's what I have! 

[generated-website.zip](https://github.com/cmu-csd-phd/csd-blog/files/7831724/generated-website.zip)

**Comment by jaybosamiya** [comment]
This is just the generated files; could you provide your inputs (i.e., without running any of the scripts, just zip the whole `csd-blog` directory) so that I could check what is wrong on the input side?

**Comment by Ananya-Joshi** [comment]
The zip file for the whole csd-blog directory is too large, so I've just zipped up the website folder. My repo has the structure I'm using: https://github.com/Ananya-Joshi/csd-blog/tree/main  
[website.zip](https://github.com/cmu-csd-phd/csd-blog/files/7833312/website.zip)

**Comment by jaybosamiya** [comment]
Ah, I see what's happened. It seems like you copied from the `website` directory rather than copying from the previous year (i.e., `website/2021/_index.md`). 

If you run `cp website/content/2021/_index.md website/content/2022/_index.md` from the root of the repository, it'll actually copy the correct file over, and it then works as expected. Do try it out and let me know

**Comment by jaybosamiya** [comment]
Also, fwiw, just to prevent this error from happening in future years, I've now pushed some code to make this check automatic going forward (https://github.com/cmu-csd-phd/csd-blog/commit/9ff3790253514c5543cee7bc12e4e422b5721d2d)

**Comment by Ananya-Joshi** [comment]
It works! Thanks!

**Comment by jaybosamiya** [comment]
Cool, glad it works!
